server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: tenant-service
              uri: lb://TENANT-SERVICE
              predicates:
                - Path=/api/tenants/**

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/customers/**

            - id: loan-service
              uri: lb://LOAN-SERVICE
              predicates:
                - Path=/api/loans/**

            - id: credit-risk-service
              uri: lb://CREDIT-RISK-SERVICE
              predicates:
                - Path=/api/risk/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

